### ISSUE TITLE
Mainpage markup bug

### ISSUE THREAD

**Issue by okplanbo** [kleinrein/lbry-community#3]
Found on the mainpage:

[Screenshot](https://prnt.sc/im5lzv)

Spotted on Firefox 58.0.2 (64b) on Windows 7. Resolution: 1366 x 768 px.
Same for Chrome 64.0.3282.119 (64b)

**Comment by kleinrein** [comment]
Thanks for reporting.
This was fixed in a commit a while ago (https://github.com/kleinrein/lbry-community/commit/037c7009673da6476b1d10f25d51f4d88f912e21) but it haven't been published yet.

Will be online in a few days. Closing the issue for now. Reopen if you still experiencing the same bug.
